language: node_js

node_js:
- '10'

services:
- mongodb

sudo: false

cache:
  directories:
  - 'node_modules'

before_script:
- npm install
- sleep 5 # thanks mongo

script:
- ./node_modules/.bin/jest test.ts