language: node_js

node_js:
- '10'

services:
- mongodb

sudo: false

cache:
  directories:
  - 'node_modules'

before_script:
- npm install
- npm install --peer reflect-metadata mongodb @nestjs/common@5.0.1 @nestjs/core@5.0.1 rxjs
- sleep 5 # thanks mongo

script:
- ./node_modules/.bin/jest --coverage
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js