language: node_js
node_js:
- '8'
- '10'
services:
- mongodb
sudo: false
cache:
  directories:
  - node_modules
before_script:
- npm install
- npm install -g coveralls lerna
- lerna bootstrap --hoist --no-ci
- sleep 2
script:
- "./node_modules/.bin/jest --coverage --detectOpenHandles"
- cat ./coverage/lcov.info | coveralls
- 
deploy:
  provider: heroku
  api_key:
    secure: AH2FFYA6n4VqZR87xRQH1y/iqrFEI6c4lEyBVkvuNpB+CE23/UUiolS8e6x/SHmSQuAtteN0BZd14nqbtqnNN+bVDiH6OA6TGtEMJOBB5sngDep5/ZCYp0wnerwgGlOAMDjOTBfPCwpiV4YPHoY1z69B9yjydyL+/WXwikK9Qy36473WmNDmD5YvjhVZ1eiPOCY2h/nu2jUcGrOzNgVEpZ1Xp9lklV+LVJz3Kr1XuXIzS1sa8YDu0yvBNpnExOht4FO3Ka40OvQu7iyKgs1KuZFehKjJFKRGEWu5qOm8Qz5b0640ycnGtmjxz3p4RzajaOr7bd37weeL4X3sa9ZVahGau1bEhAQlpfTydwOFguVEn2cscZUMFGWT1FaPQddf5lGQkAAHwGLRX1luwstCLwWjWF4cgV5LFvOq4oJAt0cv4iXl5A2EVCTt9LaECU83Q43elCd9TlSpM/NDtxi/bSHLsmJDX5Bv25MYnObwAy4wkfWgzR515RVjW5PUXhvOwCY+/S7rQ8Tgmx9pfo/jhM5VuJ/AbAOc+wAGR/9Lv/9kN9av4AOpjjiIiQ6VnFYfKEhvIhKzbDO+SM0g4WnBJPWuLv8ITpFiWsDNwMcFgJbOM6EEXF5m5gypDaK2P2jpdSQ3K2l6EwQ7oYsBUEZTwRRbYHAIjep7ghOlAlsUq5s=
  app: marcj-marshal
  on:
    repo: marcj/marshal.ts
